title: DSestu's knowledge repo 
description: This place contains some knowledge that I find helpful in my everyday work
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Source: https://github.com/DSestu/knowledge

search_enabled: true
color_scheme: dark